### ISSUE TITLE
Keep the kernel module code to a minimum

### ISSUE THREAD

**Issue by themighty1** [Douane/douane-dkms#11]
I noticed that you are struggling with a kernel panic in another issue.
My question is: is this by design that you prefer not to 
1. loop through /proc/<PID>/fd entries in the daemon but instead prefer to do it in the kernel module.
2. Keep the rules list in daemon instead of in the module.
3. Look up the exe path in /proc in daemon instead of locking/unlocking a running task in the module.

I understand that doing all the above in the module vs userspace is faster. I was just wondering whether there is some other rationale apart from the speed-up.

**Comment by zedtux** [comment]
@themighty1 I'm closing the issue as I'm not going to change the way I did the implementation but anyway in the case someone has suggestion or want to discuss this point he can use this issue.
