### ISSUE TITLE
Error 127 when issuing make dkms 

### ISSUE THREAD

**Issue by jadedevin13** [Douane/douane-dkms#14]
Installing Douane Linux kernel module version 0.8.2...
make: dkms: Command not found
Makefile:77: recipe for target 'dkms' failed
make: *** [dkms] Error 127

**Comment by jadedevin13** [comment]
Solved by installing dkms
apt-get install dkms

**Comment by mike394** [comment]
└─$ sudo apt-get install dkms                       
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
E: Unable to locate package dkms
