### ISSUE TITLE
Compilation: make error 10 "ERROR (dkms apport): binary package for douane: 0.8.2 not found"

### ISSUE THREAD

**Issue by primaclip** [Douane/douane-dkms#17]
Hi,
thanks for your efforts with this promising-looking software!
I'm trying to follow your compilation instructions and get stuck at the kernel module part. After installing all dependencies, I did the following (terminal-output) and got an error (since I don't completely understand how the make-process works, I have to ask this way. Hope you can help me with the info provided):

```
bims@bimstop:~/.source$ git clone https://github.com/Douane/douane-dkms
Klone nach 'douane-dkms' ...
remote: Counting objects: 76, done.
remote: Total 76 (delta 0), reused 0 (delta 0), pack-reused 76
Entpacke Objekte: 100% (76/76), Fertig.
Prüfe Konnektivität ... Fertig.
bims@bimstop:~/.source$ cd douane-dkms/
bims@bimstop:~/.source/douane-dkms$ sudo make dkms
Installing Douane Linux kernel module version 0.8.2...

Creating symlink /var/lib/dkms/douane/0.8.2/source ->
                 /usr/src/douane-0.8.2

DKMS: add completed.

Kernel preparation unnecessary for this kernel.  Skipping...

Building module:
cleaning build area....
make KERNELRELEASE=4.4.0-22-generic -C /lib/modules/4.4.0-22-generic/build M=/var/lib/dkms/douane/0.8.2/build.....(bad exit status: 2)
ERROR (dkms apport): binary package for douane: 0.8.2 not found
Error! Bad return status for module build on kernel: 4.4.0-22-generic (x86_64)
Consult /var/lib/dkms/douane/0.8.2/build/make.log for more information.
Makefile:77: die Regel für Ziel „dkms“ scheiterte
make: *** [dkms] Fehler 10

```
[make.log.txt](https://github.com/Douane/douane-dkms/files/259088/make.log.txt)

**Comment by zedtux** [comment]
Hello @primaclip and thank you for your issue :)

It looks like you're using Kernel 4.4, right? Can you please give a try to [this PR](https://github.com/Douane/douane-dkms/pull/15) ?

**Comment by primaclip** [comment]
I'd love to try it out - but I'm too unexperienced with git and compiling and so on..:

1. i don't know how to exchange the original code with the PR via git -- but I helped myself by just copying the raw text into the file

2.  but then the "make"-commands return errors like "folder already existing" or "Error! DKMS tree already contains: douane-0.8.2
You cannot add the same module/version combo more than once." How do I remove those results of the first unsuccessful attempt, so I can try from start?

Sorry for these basic questions..

**Comment by zedtux** [comment]
No problem @primaclip :)

> i don't know how to exchange the original code with the PR via git

It's an easy step when you did it already once. Here is how to do it:

 1. Clone the forked repo: `git clone https://github.com/smarek/douane-dkms douane-dkms-smarek` (The `douane-dkms-smarek` at the end means use this name instead of repository name. The idea is to not have a conflict with the official Douane repository)
 2. CD to the folder: `cd douane-dkms-smarek`
 3. Checkout the right branch (By default the `master` branch will be checked out, but smarek has created a branch where the code is): `git checkout fix-kernel-freeze` (the branch name can been found [here](https://github.com/smarek/douane-dkms/branches))

Now you have the right code, you can follow the building instruction like you did before with the official branch.

> the "make"-commands return errors like "folder already existing" or "Error! DKMS tree already contains: douane-0.8.2

This is because you have to clean your kernel between to build of the kernel module (done automatically when doing `make dkms` because I have built the `Makefile` in order to do it).

You have to use the `dkms` command in order to do it but to ease your life, you can use `make cleandkms` in the `douane-dkms` folder (official repository) in order to remove completely the kernel module.

But here, to make your life even easier, I have added the `make rebuilddkms` command which will clean the existing kernel module from the kernel and then build the module from the repository where you're running the command so that if you do it from the `douane-dkms-smarek` folder, you'll have the new code.

Feel free to ask for more information if needed.

**Comment by datapharmer** [comment]
I attempted this and it failed. Here is the output:

sudo make rebuilddkms
make cleandkms; \
make dkms
make[1]: Entering directory '/home/kevin/Douane/douane-dkms-smarek'
Removing Douane Linux kernel module...

------------------------------
Deleting module version: 0.8.2
completely from the DKMS tree.
------------------------------
Done.
make[1]: Leaving directory '/home/kevin/Douane/douane-dkms-smarek'
make[1]: Entering directory '/home/kevin/Douane/douane-dkms-smarek'
Installing Douane Linux kernel module version 0.8.2...

Creating symlink /var/lib/dkms/douane/0.8.2/source ->
                 /usr/src/douane-0.8.2

DKMS: add completed.

Kernel preparation unnecessary for this kernel.  Skipping...

Building module:
cleaning build area....
make KERNELRELEASE=4.4.0-24-generic -C /lib/modules/4.4.0-24-generic/build M=/var/lib/dkms/douane/0.8.2/build....(bad exit status: 2)
ERROR (dkms apport): binary package for douane: 0.8.2 not found
Error! Bad return status for module build on kernel: 4.4.0-24-generic (x86_64)
Consult /var/lib/dkms/douane/0.8.2/build/make.log for more information.
Makefile:77: recipe for target 'dkms' failed
make[1]: *** [dkms] Error 10
make[1]: Leaving directory '/home/kevin/Douane/douane-dkms-smarek'
Makefile:103: recipe for target 'rebuilddkms' failed
make: *** [rebuilddkms] Error 2

**Comment by bash64** [comment]
sudo make dkms
Installing Douane Linux kernel module version 0.8.2...

Creating symlink /var/lib/dkms/douane/0.8.2/source ->
                 /usr/src/douane-0.8.2

DKMS: add completed.

Kernel preparation unnecessary for this kernel.  Skipping...

Building module:
cleaning build area....
make KERNELRELEASE=4.4.0-24-generic -C /lib/modules/4.4.0-24-generic/build M=/var/lib/dkms/douane/0.8.2/build....(bad exit status: 2)
Error! Bad return status for module build on kernel: 4.4.0-24-generic (x86_64)
Consult /var/lib/dkms/douane/0.8.2/build/make.log for more information.
Makefile:77: recipe for target 'dkms' failed
make: *** [dkms] Error 10

**Comment by zedtux** [comment]
So for me, this is a compilation issue with the kernel 4.4. @smarek do you have any comment about this?

**Comment by bash64** [comment]
I did do rebuilddkms first and it failed. I then went into the original dkms folder and did make cleandkms. then came back and tried sudo make dkms on the new branch and got the above error. I wouldn't mind trying a lower kernel, however, mint 18 comes with a minimum of 4.4.0-21.

**Comment by zedtux** [comment]
@bash64 I think there is a compilation issue.

**Comment by bash64** [comment]
I am working on my 2nd ebook. I expect to finish it in about 30 days. Douane has a chapter in it right now. Need to get something working before release or I will have to leave Douane out.

**Comment by zedtux** [comment]
Ho, really? That's nice!! 👍 @smarek do you have an input on this?

**Comment by smarek** [comment]
This is already being reported in #18 probably should be one or another issue closed as duplicate. Also we need the build logs to debug anything.

**Comment by bash64** [comment]
ok, i posted to #18.

**Comment by AlisaKitty** [comment]
cd
mkdir Douane
cd Douane/
git clone https://github.com/smarek/douane-dkms douane-dkms-smarek
```
Cloning into 'douane-dkms-smarek'...
remote: Counting objects: 79, done.
remote: Total 79 (delta 0), reused 0 (delta 0), pack-reused 79
Unpacking objects: 100% (79/79), done.
Checking connectivity... done.
```
cd douane-dkms-smarek
git checkout fix-kernel-freeze
```
Branch fix-kernel-freeze set up to track remote branch fix-kernel-freeze from origin.
Switched to a new branch 'fix-kernel-freeze'
```
sudo make dkms
```
Installing Douane Linux kernel module version 0.8.2...
mkdir: cannot create directory ‘/usr/src/douane-0.8.2’: File exists
Makefile:77: recipe for target 'dkms' failed
make: *** [dkms] Error 1
```

**Comment by AlisaKitty** [comment]
git clone https://github.com/smarek/douane-dkms-smarekCloning into 'douane-dkms-smarek'...
Username for 'https://github.com':

**Comment by zedtux** [comment]
```
git clone https://github.com/smarek/douane-dkms-smarek
```

Is not correct, you have to do

```
git clone https://github.com/smarek/douane-dkms douane-dkms-smarek
```

as you did.

Before you have to uninstall the old version. From the original version you need to use `sudo make dkmsclean` and then follow the instructions.

**Comment by AlisaKitty** [comment]
```
sudo make dkmsclean
make: *** No rule to make target 'dkmsclean'.  Stop.

sudo make dkms
Installing Douane Linux kernel module version 0.8.2...
mkdir: cannot create directory ‘/usr/src/douane-0.8.2’: File exists
Makefile:77: recipe for target 'dkms' failed
make: *** [dkms] Error 1

```

**Comment by cmalkus** [comment]
Having the same issue.

`$ sudo make cleandkms 
Removing Douane Linux kernel module...

------------------------------
Deleting module version: 0.8.2
completely from the DKMS tree.
------------------------------
Done.
$ git status
On branch fix-kernel-freeze
Your branch is up-to-date with 'origin/fix-kernel-freeze'.
nothing to commit, working directory clean
$ sudo make dkms 
Installing Douane Linux kernel module version 0.8.2...

Creating symlink /var/lib/dkms/douane/0.8.2/source ->
                 /usr/src/douane-0.8.2

DKMS: add completed.

Kernel preparation unnecessary for this kernel.  Skipping...

Building module:
cleaning build area....
make KERNELRELEASE=4.4.0-31-generic -C /lib/modules/4.4.0-31-generic/build M=/var/lib/dkms/douane/0.8.2/build....(bad exit status: 2)
ERROR (dkms apport): binary package for douane: 0.8.2 not found
Error! Bad return status for module build on kernel: 4.4.0-31-generic (x86_64)
Consult /var/lib/dkms/douane/0.8.2/build/make.log for more information.
Makefile:77: recipe for target 'dkms' failed
make: *** [dkms] Error 10`

**Comment by zedtux** [comment]
@primaclip, @datapharmer, @bash64 @AlisaKitty, @smarek and @cmalkus you have to use the @Guimli's fork https://github.com/Guimli/douane-dkms.

He is working very hard on fixing the kernel module issues and all the tests I'm doing as of now shown that the module is much more stable.

So please run `sudo make cleandkms` and then `git clone https://github.com/Guimli/douane-dkms douane-dkms-guimli` and use that new folder in order to compile the kernel module.

**Comment by cmalkus** [comment]
This got my daemon running, but when it is, all my connections timeout and no dialogs are presented.
When I start douane-dialog with the -D flag, I get this:
```
$ /opt/douane/bin/douane-dialog -D
Failed to register: Timeout was reached
```
The log looks like this
```

07/08/2016 23:22:23 | dialog |  INFO | [main.cpp::Main:205]: The log file is /var/log/douane.log
07/08/2016 23:22:23 | dialog | DEBUG | [main.cpp::Main:208]: The debug mode is enabled
07/08/2016 23:22:23 | dialog | DEBUG | [main.cpp::Main:210]: GTKmm version: 3.18.0
07/08/2016 23:22:23 | dialog | DEBUG | [main.cpp::Main:215]: Gtk::Application::create()
07/08/2016 23:22:23 | dialog | DEBUG | [main.cpp::Main:229]: Initializing GTK window
07/08/2016 23:22:23 | dialog | DEBUG | [tools.cpp::Tools:21]: Douane root path is /opt/douane/bin
07/08/2016 23:22:23 | dialog | DEBUG | [gtk/gtk_question_window.cpp::GtkQuestionWindow:20]: /opt/douane/data/douane_128.png
07/08/2016 23:22:23 | dialog | DEBUG | [tools.cpp::Tools:21]: Douane root path is /opt/douane/bin
07/08/2016 23:22:23 | dialog | DEBUG | [tools.cpp::Tools:21]: Douane root path is /opt/douane/bin
07/08/2016 23:22:24 | dialog | DEBUG | [main.cpp::Main:232]: Initializing DBusClient
07/08/2016 23:22:24 | dialog | DEBUG | [dbus/dbus_client.cpp::DBusClient:8]: Initializing D-Bus client...
07/08/2016 23:22:24 | dialog | DEBUG | [dbus/douane.cpp::Douane:7]: Douane::Douane()
07/08/2016 23:22:24 | dialog | DEBUG | [dbus/dbus_client.cpp::DBusClient:15]: D-Bus client Initialized
07/08/2016 23:22:24 | dialog | DEBUG | [main.cpp::Main:252]: Starting D-Bus client
07/08/2016 23:22:24 | dialog | DEBUG | [main.cpp::Main:255]: Entering GTK loop
07/08/2016 23:22:24 | dialog | DEBUG | [dbus/dbus_client.cpp::DBusClient:27]: Starting D-Bus client...
07/08/2016 23:22:49 | dialog | DEBUG | [dbus/dbus_client.cpp::DBusClient:20]: Shutting down D-Bus client..
07/08/2016 23:24:54 | dialog |  INFO | [main.cpp::Main:205]: The log file is /var/log/douane.log
07/08/2016 23:24:54 | dialog | DEBUG | [main.cpp::Main:208]: The debug mode is enabled
07/08/2016 23:24:54 | dialog | DEBUG | [main.cpp::Main:210]: GTKmm version: 3.18.0
07/08/2016 23:24:54 | dialog | DEBUG | [main.cpp::Main:215]: Gtk::Application::create()
07/08/2016 23:24:54 | dialog | DEBUG | [main.cpp::Main:229]: Initializing GTK window
07/08/2016 23:24:54 | dialog | DEBUG | [tools.cpp::Tools:21]: Douane root path is /opt/douane/bin
07/08/2016 23:24:54 | dialog | DEBUG | [gtk/gtk_question_window.cpp::GtkQuestionWindow:20]: /opt/douane/data/douane_128.png
07/08/2016 23:24:54 | dialog | DEBUG | [tools.cpp::Tools:21]: Douane root path is /opt/douane/bin
07/08/2016 23:24:54 | dialog | DEBUG | [tools.cpp::Tools:21]: Douane root path is /opt/douane/bin
07/08/2016 23:24:55 | dialog | DEBUG | [main.cpp::Main:232]: Initializing DBusClient
07/08/2016 23:24:55 | dialog | DEBUG | [dbus/dbus_client.cpp::DBusClient:8]: Initializing D-Bus client...
07/08/2016 23:24:55 | dialog | DEBUG | [dbus/douane.cpp::Douane:7]: Douane::Douane()
07/08/2016 23:24:55 | dialog | DEBUG | [dbus/dbus_client.cpp::DBusClient:15]: D-Bus client Initialized
07/08/2016 23:24:55 | dialog | DEBUG | [main.cpp::Main:252]: Starting D-Bus client
07/08/2016 23:24:55 | dialog | DEBUG | [main.cpp::Main:255]: Entering GTK loop
07/08/2016 23:24:55 | dialog | DEBUG | [dbus/dbus_client.cpp::DBusClient:27]: Starting D-Bus client...
07/08/2016 23:25:20 | dialog | DEBUG | [dbus/dbus_client.cpp::DBusClient:20]: Shutting down D-Bus client..
07/08/2016 23:25:22  INFO: The log file is /var/log/douane.log
07/08/2016 23:25:22  INFO: Loaded 164 Freedesktop desktop files
07/08/2016 23:25:22  INFO: Loaded 0 rules
07/08/2016 23:25:23  INFO: Currently 1 pending rules
```

`07/08/2016 23:25:23  INFO: Currently 1 pending rules` repeats a lot. I assume that means its waiting for me to accept or deny a network request, but the dialog never appears

**Comment by zedtux** [comment]
> This got my daemon running, but when it is, all my connections timeout and no dialogs are presented.

Okay so it's a step forward 👍 

> Failed to register: Timeout was reached

Well I never saw this error before... That's strange.

> `07/08/2016 23:25:23 INFO: Currently 1 pending rules` repeats a lot. I assume that means its waiting for me to accept or deny a network request, but the dialog never appears

Exactly, the firewall is doing his job (blocking all communication of the unknown applications) and yes until you validates it, the application will be blocked.

Now why you have this issue, I don't know, really. I have the same version than you and all is working fine.
The only thing I can recommend you for now is to clean everything and follow again the documentation from the start.

**Comment by cmalkus** [comment]
One thing I noticed was the files in the douane-dialog directory have been changed since building from guimli's branch. When I do a git status I see this:

```
$ git status
On branch master
Your branch is up-to-date with 'origin/master'.
Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

	modified:   dbus/dbus_client.h
	modified:   dbus/douane.h

no changes added to commit (use "git add" and/or "git commit -a")
```

I will try to start from scratch tomorrow. Thanks for all your help so far.

**Comment by zedtux** [comment]
This is a fixed I have merged this week-end in order to fix the compilation of the dialog application. Let's us know if it solves your issue or not :)

**Comment by zedtux** [comment]
I close this issue as I have merge @Guimli's PR which fixes this issue.

**Comment by cmalkus** [comment]
I tried starting the dialog again, and it worked! Well I crashed right after showing the first dialog, but I restarted it and now it seems to be behaving normally.

**Comment by zedtux** [comment]
Thank you @cmalkus for your feedback. The bug you got is known but we don't have an existing issue in the [Dialog repository](https://github.com/Douane/douane-dialog/issues). So if you can open one, that would be great :)
