### ISSUE TITLE
Make dkms error

### ISSUE THREAD

**Issue by AlisaKitty** [Douane/douane-dkms#19]
Ubuntu 16.04
```
sudo make dkms
Installing Douane Linux kernel module version 0.8.2...
mkdir: cannot create directory ‘/usr/src/douane-0.8.2’: File exists
Makefile:77: recipe for target 'dkms' failed
make: *** [dkms] Error 1
```

**Comment by zedtux** [comment]
@AlisaKitty you need to use the @smarek's PR [here](https://github.com/Douane/douane-dkms/pull/15). Follow the instructions from [this comment](https://github.com/Douane/douane-dkms/issues/17#issuecomment-222370707) in case you don't know how to proceed.

**Comment by AlisaKitty** [comment]
okey

**Comment by zedtux** [comment]
I close this issue as I have merge @Guimli's PR which fixes this issue.

**Comment by ghost** [comment]
the repo got deleted i think, its already 3 years, but I need douane to work

**Comment by zedtux** [comment]
Hey @SlightlyWindyHub, have a look at this repo's homepage, [Douane has moved to Gitlab](https://gitlab.com/douaneapp/douane-dkms) !

This issue has been imported [here](https://gitlab.com/douaneapp/douane-dkms/issues/19).

If you have any issue, please [open a ticket](https://gitlab.com/douaneapp/douane-dkms/issues/new).
