### ISSUE TITLE
upstreaming kernel module?

### ISSUE THREAD

**Issue by deathtrip** [Douane/douane-dkms#20]
Any plans to move the module into the meinline kernel?
It would solve problems with using secure boot, as it prevents using custom modules, and reduce maintaince cost.

**Comment by zedtux** [comment]
I would love it @deathtrip but the kernel module is not stable yet and I have not time yet to stabilise it.
In a ideal world, Douane would be stable and super popular and integrated to almost all Linux distributions :)

**Comment by zedtux** [comment]
@deathtrip for your information, the kernel module stability is increasing! It's not yet ready but we moved forward.

Do you know what is the process of moving the module to the mainline kernel?

**Comment by deathtrip** [comment]
here's a guide from the official kernel website:
https://www.kernel.org/doc/Documentation/SubmittingPatches

Glad to hear the module is getting more stable. Keep up the good work

**Comment by zedtux** [comment]
This repo has moved to GitLab and this issue has been imported. You can access it [here](https://gitlab.com/douaneapp/douane-dkms/issues/20).
