### ISSUE TITLE
Installing the unsigned douane kernel in Ubuntu 16.04.1 

### ISSUE THREAD

**Issue by x-solid** [Douane/douane-dkms#23]
If the ubuntu kernel was compiled with a config file /boot/conf* the enforcement for signed kernel modules was enabled
`CONFIG_MODULE_SIG=y`
`CONFIG_MODULE_SIG_ALL=y`
Ubuntu kernel won't load any module not being signed, as refered to this [SO answer](http://stackoverflow.com/questions/24975377/kvm-module-verification-failed-signature-and-or-required-key-missing-taintin) and my issue [here](https://github.com/Douane/Douane/issues/65).

If Ubuntu enforces verified kernels, possibly depends on secure boot option in BIOS. This is mentioned in this interesting [LINK](http://askubuntu.com/questions/773734/how-to-install-module-ko-module-without-kernel-signature-or-kernel-rebuild-in-ub/827534), which describes signing kernel modules, too.

**Comment by zedtux** [comment]
This repo has moved to GitLab and this issue has been imported. You can access it [here](https://gitlab.com/douaneapp/douane-dkms/issues/23).
