### ISSUE TITLE
Add new rule type to sort traffic into a user specified class of classy tc qdisk, when a classy qdisk is in use

### ISSUE THREAD

**Issue by solenskiner** [Douane/douane-dkms#4]
This would allow user to e.g. put downloads into a background class, surfing and streaming videos into a best-effort class and ssh voip and games into an interactive class.

**Comment by zedtux** [comment]
This repo has moved to GitLab and this issue has been imported. You can access it [here](https://gitlab.com/douaneapp/douane-dkms/issues/4).
