### ISSUE TITLE
Add a ruletype which takes a list of like ip netmask portstart-portend combinations or something like that, and also a boolean whether it should act as a whitelist or blacklist.

### ISSUE THREAD

**Issue by solenskiner** [Douane/douane-dkms#5]
Whitelisting could be used to secure e.g. a special banking browser against an attacker trying to redirect the user somwhere or inject resources from other servers.

Whitelisting could also be used to confine an app to be able to communicate with only localhost, or only with the LAN with a simple 255.255.255.0 netmask.

Blacklisting could e.g. be used to implement like fail2ban or peerguardian functionality.

**Comment by zedtux** [comment]
This repo has moved to GitLab and this issue has been imported. You can access it [here](https://gitlab.com/douaneapp/douane-dkms/issues/5).
